import java.awt.Color;
import javax.swing.*;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
        
        
public class JanelaPrincipal extends JFrame {
    
    //Componentes
    JButton cmd_sair;
    
    //Eventos
    ActionListener cmd_sair_click;
    
    public JanelaPrincipal() {
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        
        //Jpanel
        JPanel painel = new JPanel();
        painel.setPreferredSize(new Dimension(600,400));
        add(painel);
        pack();
        setLocationRelativeTo(null);
        painel.setBackground(Color.BLUE);
        
        
        //Evento
        cmd_sair_click = new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
            System.exit(0);
            }
        
        };
        
        //botao
        cmd_sair = new JButton("Sair");
        
        painel.add(cmd_sair);
        cmd_sair.addActionListener(cmd_sair_click);
        setVisible(true);
        
    
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
	JFrame janela = new JFrame("Meu primeiro frame em Java");
	janela.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
